import "./globals.css";
import { Bai_Jamjuree, Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});
const BaiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-baiJamjuree",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${BaiJamjuree.variable}  font-sans bg-gray-900 text-gray-100`} >
        {children}
      </body>
    </html>
  );
}
